algoritmo "semnome"
// Função :
// Autor :
// Data : 20/09/2022
// Seção de Declarações 
var
contador,soma,qtde:inteiro
media:real
inicio
para contador de 1 ate 200 faca
 se contador mod 2 <> 0  entao
 escreval(contador)
 soma <- soma + contador
 qtde <- qtde + 1
 fimse
fimpara
 media <- soma/qtde
escreval("a soma de todos os impares e:",soma)
escreval("a media e",media)


escreval
fimalgoritmo
