algoritmo "trocar valores"
// Função :
// Autor :
// Data : 08/03/2022
// Seção de Declarações 
var
  a:inteiro
  b:inteiro
  c:inteiro
inicio
// Seção de Comandos 
a <- 10
b <- 20
escreval ("valores originais das varieveis")
escreval ("valor da variavel a -->" ,a)
escreval ("valor da varievel b -->",b)
c <- a
a <- b
b <- c
escreval ("resultado da troca de valores")
escreval ("valor da vareavel a -->", a)
escreval ("valor da vareavel b -->", b)
fimalgoritmo
