algoritmo "semnome"
// Função :
// Autor :
// Data : 30/08/2022
// Seção de Declarações 
var
contador,numero,resultado:inteiro
inicio
escreval ("digite um numero")
leia(numero)
resultado <- 1
se (numero = 0) entao
escreval ("resultado => 1",resultado)
senao
para contador de 1 ate numero faca
resultado <- resultado * contador
fimpara
fimse
escreval(" resultado =>",resultado)
fimalgoritmo
