algoritmo "calcular media"
// Função :cslcular a media de 2 notas
// Autor : igor
// Data : 26/04/2022
// Seção de Declarações 
var
p1:real
p2:real
media:real
inicio
// dados de entrada
escreval ("entre com valor para p1")
leia (p1)
escreval("entre com valor para p2")
leia(p2)
// fim dos dados de entrada

// processamento
media <- (p1+p2)/2
//fim do procesamento
// dados de saida
escreval ("a media do eluno e: ",media)
// fim dos dados de saida
fimalgoritmo
